### ISSUE TITLE
can you rename the font to the original name?

### ISSUE THREAD

**Issue by Firestar-Reimu** [Happypig375/AMSFonts-Ttf-Otf#1]
can you rename the font to the original name? like `cmr5 cmr7 cmr10 lasy5 eusb10`

**Comment by Happypig375** [comment]
Unfortunately I do not have the mapping. You can try going through the procedure yourself though, because I don't remember if I renamed them or it's the artifact of the software I used.

**Comment by Firestar-Reimu** [comment]
Thanks! I found that I can use **the free software fontforge** to generate otf from pfb, so I do not need to spend $97 (or >600 RMB for me). You can see this:

https://fontforge.org/docs/faq.html#faq-outline-conversion

> How do I convert from one outline format to another?
> The simple answer that will work if you want something quick is:
> [File->Generate Fonts](https://fontforge.org/docs/ui/dialogs/generate.html)
> to generate the desired output.
> If you are converting from one PostScript format to another (pfb to otf, for example) that’s all you need to do.

or this: https://fontforge.org/docs/tutorial/scripting-tutorial.html

**Comment by Happypig375** [comment]
You can update the files if you want, I'm giving you collaborator permission

**Comment by Firestar-Reimu** [comment]
多谢晒啦
