### ISSUE TITLE
Large descent settings on some fonts

### ISSUE THREAD

**Issue by jonschz** [Happypig375/AMSFonts-Ttf-Otf#2]
Hi,

first of all, thank you very much for creating this repository, it really made a difference for me. I have encountered a minor problem with the fonts in `amsfonts-otf.zip`, specifically `CMBSYx.otf` and `CMSYx.otf` (although others are likely affected as well). The `descent` value on these is so high that using them in block text is borderline impossible. The following is set in default leading (single space): 
![grafik](https://user-images.githubusercontent.com/17198703/195802265-65ddf2a7-4719-4773-8deb-e1c994035bfe.png)
I used an online font editor to set the descent value to a more reasonable value of `-212/1000 em`:
![grafik](https://user-images.githubusercontent.com/17198703/195802543-2e02f549-4ea3-44fd-bb38-ce8081431639.png)
My question is: Can this process be automated in a sensible way? I hardly know anything about editing fonts.

**Comment by Happypig375** [comment]
Does the FontForge conversion have the same problem? Here: https://github.com/Firestar-Reimu/AMSFonts-OTF

**Comment by jonschz** [comment]
Hi! I have just checked. At the very least, `CMSY10.otf` in the repository you linked has the same problem.

**Comment by Happypig375** [comment]
@jonschz Thanks for checking, it seems this is a problem in the original font then. If you know programming, you can use FontForge as a library here https://fontforge.org/docs/scripting/python.html and do similar conversions for every font file.

**Comment by jonschz** [comment]
Thanks for the response! As I do not use this font at the moment, it is unlikely that I will put any work into it any time soon. Still, thanks for showing where to look if one wants to fix it - maybe someone else will need it in the future. Feel free to close this ticket.

**Comment by Happypig375** [comment]
You're welcome!
